const UNIX_SECOND = 1_000;
const UNIX_MINUTE = 60 * UNIX_SECOND;
const UNIX_HOUR = 60 * UNIX_MINUTE;
const UNIX_DAY = 24 * UNIX_HOUR;
const UNIX_MONTH = 30 * UNIX_DAY;
const UNIX_YEAR = 365 * UNIX_DAY;

export const UNIX = {
  SECOND: UNIX_SECOND,
  MINUTE: UNIX_MINUTE,
  HOUR: UNIX_HOUR,
  DAY: UNIX_DAY,
  MONTH: UNIX_MONTH,
  YEAR: UNIX_YEAR,
} as const;
